#!/bin/sh

tmpdir="/tmp/$$-tiff-compression-ratio"
mkdir "$tmpdir"

for i in "$@"; do
    tiffcp -c none "$i" "$tmpdir/$i" 2>/dev/nul
    fullsize="$(stat -c '%s' "$tmpdir/$i")"
    compsize="$(stat -c '%s' "$i")"
    let reducedby='fullsize-compsize'
    let compratio='reducedby*1000/fullsize'
    printf '%03d‰: %s\n' $compratio "$i"
done
