.TH tiff-compression-ratio 1 tiff-compression-ratio\-0.0.1
.SH NAME
tiff-compression-ratio \- determine the compression ratio of one or more tiffs
.SH SYNOPSIS
.B tiff-compression-ratio FILE [FILE2...]
.SH DESCRIPTION
.B tiff-compression-ratio
checks the compression ratio of each tiff specified on the command line.
.SH OPTIONS
none
.SH FILES
.SH SEE ALSO
.SH BUGS
Probably.
.SH LICENSE
Copyright 2013 
.sp
You may use this software however you like.
